### ISSUE TITLE
"on-demand" value for "hover" media feature is not valid

### ISSUE THREAD

**Issue by julienzakaib** [rafgraph/detect-hover#1]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@media) , the [`hover` media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover) supports `hover` and `none` as values. It looks like you don't need to check for `on-demand` as well. It looks like only [`any-hover`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/any-hover) supports that value.

**Comment by rafgraph** [comment]
The hover on-demand value was removed from the [July 6th 2016 W3C Media Queries Level 4][w3cSpec7-6-2016] draft specification, but was included in the [previous draft (January 26th 2016)][w3cSpec1-26-2016] of the spec. Any device that registers as having hover on-demand capabilities will show up as hover `none` in `detectHover`'s state.

I still check for hover `on-demand` (and map it to hover `none`) because it was very prevalent on Android phones prior to spec change.

[w3cSpec7-6-2016]: https://www.w3.org/TR/2016/WD-mediaqueries-4-20160706/#hover
[w3cSpec1-26-2016]: https://www.w3.org/TR/2016/WD-mediaqueries-4-20160126/#hover
